config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: 'items#index', as: 'welcome'

  resources :items, except: %i[new create] do
    resources :reviews, only: %i[new create]
  end

  resources :merchants do
    resources :items, only: %i[new create index]
  end

  resources :reviews, only: %i[edit update destroy]

  resources :orders, only: %i[new create show]

  get '/profile/addresses/new', to: 'addresses#new'
  get '/profile/addresses/:id/edit', to: 'addresses#edit'
  patch '/profile/addresses/:id', to: 'addresses#update'
  post '/profile/addresses', to: 'addresses#create'
  delete '/profile/addresses/:id', to: 'addresses#destroy'

  post '/cart/:item_id', to: 'cart#add_item'
  get '/cart', to: 'cart#show'
  delete '/cart', to: 'cart#empty'
  delete '/cart/:item_id', to: 'cart#remove_item'
  patch '/cart/:item_id/:increment_decrement', to: 'cart#increment_decrement'

  get '/register', to: 'users#new'
  post '/users', to: 'users#create'
  get '/profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit_profile'
  get '/profile/edit_password', to: 'users#edit_password'
  patch '/profile/update', to: 'users#update_profile'
  patch '/profile/update_password', to: 'users#update_password'

  get '/profile/orders', to: 'user_orders#index'
  get '/profile/orders/:id', to: 'user_orders#show', as: 'profile_order'
  patch '/profile/orders/:id', to: 'user_orders#update'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create', as: 'login_create'
  delete '/logout', to: 'sessions#logout'

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/users', to: 'users#index'
    get '/users/:user_id', to: 'users#show'
    patch '/users/:user_id', to: 'users#toggle_enabled'
    get '/users/:user_id/edit', to: 'users#edit_profile'
    patch '/users/:user_id/update', to: 'users#update_profile', as: 'update_user_profile'
    get '/users/:user_id/orders/:order_id', to: 'user_orders#show', as: 'user_order'
    patch '/users/:user_id/orders/:order_id', to: 'user_orders#update', as: 'user_order_update'
    patch '/orders/:order_id', to: 'dashboard#update_order_status'
    get '/merchants/:merchant_id', to: 'merchants#show', as: 'merchants'
    patch '/merchants/:merchant_id', to: 'merchants#toggle_enabled'
  end

  namespace :merchant do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/items', to: 'items#index', as: 'user_items'

    get '/orders/:order_id', to: 'orders#show', as: 'orders'
    patch '/orders/:order_id/:item_order_id/fulfill', to: 'orders#update_item'

    get '/items/new', to: 'items#new'
    get '/items/:item_id/edit', to: 'items#edit', as: 'items_edit'
    post '/items', to: 'items#create'
    patch '/items/:item_id', to: 'items#update', as: 'items_update'
    patch '/items/:item_id/activate_deactivate/:activate_deactivate', to: 'items#activate_deactivate', as: 'items_activate_deactivate'
    patch '/items/disable/:item_id', to: 'items#disable_item', as: 'item_disable'
  end
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :item_orders, through: :items
  has_many :users

  validates_presence_of :name,
                        :address,
                        :city,
                        :state,
                        :zip

  validates_inclusion_of :enabled?, in: [true, false]

  def no_orders?
    item_orders.empty?
  end

  def item_count
    items.where(active?: true).count
  end

  def average_item_price
    items.where(active?: true).average(:price)
  end

  def distinct_cities
    item_orders.distinct.joins(order: [:user, :address])
      .where('"users"."enabled?" = \'t\'')
      .pluck('addresses.city')
  end

  def specific_orders
    item_orders.group(:order_id)
      .select('item_orders.order_id, sum(quantity) as order_total_quantity,
        sum(quantity * item_orders.price) as order_total_cost'
      )
  end
end

app/controllers/admin/merchants_controller.rb
# frozen_string_literal: true

class Admin::MerchantsController < Admin::BaseController
  def show
    @merchant = Merchant.find(params[:merchant_id])
  end

  def toggle_enabled
    merchant = Merchant.find(params[:merchant_id])
    is_enabled = merchant.enabled?
    merchant.update_attributes(enabled?: !is_enabled)
    merchant.items.update(active?: !is_enabled)
    if !is_enabled
      flash[:success] = "#{merchant.name} has been enabled!"
    else
      flash[:success] = "#{merchant.name} has been disabled!"
    end
    redirect_to merchants_path
  end
end

app/controllers/merchant/base_controller.rb
# frozen_string_literal: true

class Merchant::BaseController < ApplicationController
  before_action :require_merchant

  def require_merchant
    render_404 unless merchant_admin? || merchant_employee?
  end
end

app/controllers/merchant/dashboard_controller.rb
# frozen_string_literal: true

class Merchant::DashboardController < Merchant::BaseController
  def index
    @merchant = current_user.merchant
  end
end

app/controllers/merchant/items_controller.rb
# frozen_string_literal: true

class Merchant::ItemsController < Merchant::BaseController
  def index
    @items = current_user.merchant.items
  end

  def new; end

  def create
    merchant = current_user.merchant
    item = merchant.items.create(item_params)
    if item.save
      flash[:success] = 'Item was successfully created!'
      redirect_to merchant_user_items_path
    else
      flash[:error] = item.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @item = Item.find(params[:item_id])
  end

  def update
    @item = Item.find(params[:item_id])
    @item.update(item_params)
    if @item.save
      flash[:success] = 'Item was successfully updated!'
      redirect_to merchant_user_items_path
    else
      flash[:error] = @item.errors.full_messages.to_sentence
      render :edit
    end
  end

  def activate_deactivate
    if params[:activate_deactivate] == 'deactivate'
      item = Item.find(params[:item_id])
      item.toggle!(:active?)
      flash[:notice] = "#{item.name} is now deactivated and is no longer for sale."
    elsif params[:activate_deactivate] == 'activate'
      item = Item.find(params[:item_id])
      item.toggle!(:active?)
      flash[:notice] = "#{item.name} is now activated and available for sale."
    end
    redirect_to merchant_user_items_path
  end

  def disable_item
    item = Item.find(params[:item_id])
    item.toggle!(:enabled?)
    flash[:notice] = "#{item.name} is now removed from #{item.merchant.name}'s online inventory."
    redirect_to merchant_user_items_path
  end

  private

  def item_params
    params[:image] = 'https://bit.ly/34a6p1g' if params[:image] == ''
    params.permit(:name, :description, :price, :inventory, :image)
  end
end

app/controllers/merchant/orders_controller.rb
# frozen_string_literal: true

class Merchant::OrdersController < Merchant::BaseController
  def show
    @order = Order.find(params[:order_id])
    @item_orders = @order.find_order(current_user.merchant_id)
  end

  def update_item
    item_order = ItemOrder.find(params[:item_order_id])
    item_order.update_attributes(status: 1)
    item_order.reduce_inventory
    flash[:success] = "The #{item_order.item.name} is now fulfilled."
    item_order.order.update_status(1) if item_order.order.all_items_fulfilled?

    redirect_to merchant_orders_path(params[:order_id])
  end
end

app/controllers/merchants_controller.rb
# frozen_string_literal: true

class MerchantsController < ApplicationController
  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end

  def new; end

  def create
    merchant = Merchant.create(merchant_params)
    if merchant.save
      redirect_to merchants_path
    else
      flash.now[:error] = merchant.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @merchant = Merchant.find(params[:id])
  end

  def update
    @merchant = Merchant.find(params[:id])
    @merchant.update(merchant_params)
    if @merchant.save
      redirect_to "/merchants/#{@merchant.id}"
    else
      flash[:error] = @merchant.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    Merchant.destroy(params[:id])
    redirect_to '/merchants'
  end

  private

  def merchant_params
    params.permit(:name, :address, :city, :state, :zip)
  end
end

app/views/merchants/edit.html.erb
<h1>Edit <%=link_to @merchant.name, "/merchants/#{@merchant.id}" %></h1>
<center>
  <%= form_tag "/merchants/#{@merchant.id}", method: :patch do %>
    <%= label_tag :name %>
    <%= text_field_tag :name, "#{@merchant.name}"%>

    <%= label_tag :address %>
    <%= text_field_tag :address, "#{@merchant.address}" %>

    <%= label_tag :city %>
    <%= text_field_tag :city, "#{@merchant.city}" %>

    <%= label_tag :state %>
    <%= text_field_tag :state, "#{@merchant.state}" %>

    <%= label_tag :zip %>
    <%= text_field_tag :zip,"#{@merchant.zip}" %>

    <%= submit_tag 'Update Merchant' %>
  <% end %>
</center>

app/views/merchants/index.html.erb
<h1 align = "center">Merchants</h1>
<% if site_admin? %>
  <h3 align="center"><%= link_to "New Merchant", "/merchants/new" %></h3>
<% end %>
<section class = "grid-container">
  <% @merchants.each do |merchant|%>
    <section class = "grid-item" id='merchant-<%= merchant.id %>'>
      <% if site_admin? %>
        <p>
          <h3><%= link_to merchant.name, admin_merchants_path(merchant) %></h3>
          <p><%= "#{merchant.city}, #{merchant.state}"%></p>
          <% if merchant.enabled? %>
            <p><%= link_to 'Disable', admin_merchants_path(merchant), method: :patch %></p>
          <% else %>
            <p><%= link_to 'Enable', admin_merchants_path(merchant), method: :patch %></p>
          <% end %>
        </p>
      <% else %>
        <p><%= link_to merchant.name, merchant_path(merchant) %></p>
      <% end %>
    </section>
  <% end %>
</section>

app/views/merchants/new.html.erb
<h1 align= "center">Create Merchant</h1>
<center>
  <%= form_tag '/merchants', method: :post do |f| %>

    <%= label_tag :name %>
    <%= text_field_tag :name %>

    <%= label_tag :address %>
    <%= text_field_tag :address %>

    <%= label_tag :city %>
    <%= text_field_tag :city %>

    <%= label_tag :state %>
    <%= text_field_tag :state %>

    <%= label_tag :zip %>
    <%= text_field_tag :zip %>

    <%= submit_tag 'Create Merchant' %>
  <% end %>
</center>

app/views/merchants/show.html.erb
<h1><%= link_to @merchant.name, "/merchants/#{@merchant.id}" %></h1>
<p class="address"><%= @merchant.address %></p>
<p class="address"><%= @merchant.city %>, <%= @merchant.state %> <%= @merchant.zip %></p>

<ul><%= link_to "All #{@merchant.name} Items", "/merchants/#{@merchant.id}/items" %></ul>
<ul><%= link_to "Update Merchant", "/merchants/#{@merchant.id}/edit" %></ul>
<ul><%= link_to "Delete Merchant", "/merchants/#{@merchant.id}", method: :delete  if @merchant.no_orders?%>
</ul>
<section class = "merchant-stats">
  <h2>Number of Items: <%=@merchant.item_count%></h2>
  <% if @merchant.item_count > 0 %>
    <h2>Average Price of Items: <%=number_to_currency(@merchant.average_item_price)%></h2>
    <section class = "distinct-cities">
      <h2>Cities that order these items:</h2>
      <% @merchant.distinct_cities.each do |city| %>
        <h3><li><%= city %></li></h3>
      <% end %>
    <% end %>
  </section>
</section>