config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: 'items#index', as: 'welcome'

  resources :items, except: %i[new create] do
    resources :reviews, only: %i[new create]
  end

  resources :merchants do
    resources :items, only: %i[new create index]
  end

  resources :reviews, only: %i[edit update destroy]

  resources :orders, only: %i[new create show]

  get '/profile/addresses/new', to: 'addresses#new'
  get '/profile/addresses/:id/edit', to: 'addresses#edit'
  patch '/profile/addresses/:id', to: 'addresses#update'
  post '/profile/addresses', to: 'addresses#create'
  delete '/profile/addresses/:id', to: 'addresses#destroy'

  post '/cart/:item_id', to: 'cart#add_item'
  get '/cart', to: 'cart#show'
  delete '/cart', to: 'cart#empty'
  delete '/cart/:item_id', to: 'cart#remove_item'
  patch '/cart/:item_id/:increment_decrement', to: 'cart#increment_decrement'

  get '/register', to: 'users#new'
  post '/users', to: 'users#create'
  get '/profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit_profile'
  get '/profile/edit_password', to: 'users#edit_password'
  patch '/profile/update', to: 'users#update_profile'
  patch '/profile/update_password', to: 'users#update_password'

  get '/profile/orders', to: 'user_orders#index'
  get '/profile/orders/:id', to: 'user_orders#show', as: 'profile_order'
  patch '/profile/orders/:id', to: 'user_orders#update'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create', as: 'login_create'
  delete '/logout', to: 'sessions#logout'

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/users', to: 'users#index'
    get '/users/:user_id', to: 'users#show'
    patch '/users/:user_id', to: 'users#toggle_enabled'
    get '/users/:user_id/edit', to: 'users#edit_profile'
    patch '/users/:user_id/update', to: 'users#update_profile', as: 'update_user_profile'
    get '/users/:user_id/orders/:order_id', to: 'user_orders#show', as: 'user_order'
    patch '/users/:user_id/orders/:order_id', to: 'user_orders#update', as: 'user_order_update'
    patch '/orders/:order_id', to: 'dashboard#update_order_status'
    get '/merchants/:merchant_id', to: 'merchants#show', as: 'merchants'
    patch '/merchants/:merchant_id', to: 'merchants#toggle_enabled'
  end

  namespace :merchant do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get '/items', to: 'items#index', as: 'user_items'

    get '/orders/:order_id', to: 'orders#show', as: 'orders'
    patch '/orders/:order_id/:item_order_id/fulfill', to: 'orders#update_item'

    get '/items/new', to: 'items#new'
    get '/items/:item_id/edit', to: 'items#edit', as: 'items_edit'
    post '/items', to: 'items#create'
    patch '/items/:item_id', to: 'items#update', as: 'items_update'
    patch '/items/:item_id/activate_deactivate/:activate_deactivate', to: 'items#activate_deactivate', as: 'items_activate_deactivate'
    patch '/items/disable/:item_id', to: 'items#disable_item', as: 'item_disable'
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :merchant
  has_many :reviews, dependent: :destroy
  has_many :item_orders
  has_many :orders, through: :item_orders

  validates_presence_of :name,
                        :description,
                        :price,
                        :image,
                        :inventory

  validates_inclusion_of :active?, in: [true, false]
  validates_inclusion_of :enabled?, in: [true, false]

  validates_numericality_of :price, greater_than: 0
  validates_numericality_of :inventory, only_integer: true
  validates_numericality_of :inventory, greater_than: 0

  def average_review
    reviews.average(:rating)
  end

  def sorted_reviews(limit, order)
    reviews.order(rating: order).limit(limit)
  end

  def no_orders?
    item_orders.empty?
  end

  def self.five_most_popular_items
    find_by_sql("select items.name, sum(quantity) as purchase_amount from items 
      inner join item_orders on item_orders.item_id = items.id 
      inner join orders on orders.id = item_orders.order_id 
      inner join users on users.id = orders.user_id 
      where \"users\".\"enabled?\" = 't' 
      group by items.name 
      order by purchase_amount desc 
      limit 5;"
    )
  end

  def self.five_least_popular_items
    find_by_sql("select items.name, sum(quantity) as purchase_amount from items 
      inner join item_orders on item_orders.item_id = items.id 
      inner join orders on orders.id = item_orders.order_id 
      inner join users on users.id = orders.user_id 
      where \"users\".\"enabled?\" = 't' 
      group by items.name 
      order by purchase_amount
      limit 5;"
    )
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    if params[:merchant_id]
      @merchant = Merchant.find(params[:merchant_id])
      @items = @merchant.items
    else
      @items = Item.all
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @merchant = Merchant.find(params[:merchant_id])
  end

  def create
    @merchant = Merchant.find(params[:merchant_id])
    item = @merchant.items.create(item_params)
    if item.save
      redirect_to "/merchants/#{@merchant.id}/items"
    else
      flash[:error] = item.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      redirect_to "/items/#{@item.id}"
    else
      flash[:error] = @item.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    Review.where(item_id: item.id).destroy_all
    item.destroy
    redirect_to '/items'
  end

  private

  def item_params
    params.permit(:name, :description, :price, :inventory, :image)
  end
end

app/controllers/merchant/items_controller.rb
# frozen_string_literal: true

class Merchant::ItemsController < Merchant::BaseController
  def index
    @items = current_user.merchant.items
  end

  def new; end

  def create
    merchant = current_user.merchant
    item = merchant.items.create(item_params)
    if item.save
      flash[:success] = 'Item was successfully created!'
      redirect_to merchant_user_items_path
    else
      flash[:error] = item.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @item = Item.find(params[:item_id])
  end

  def update
    @item = Item.find(params[:item_id])
    @item.update(item_params)
    if @item.save
      flash[:success] = 'Item was successfully updated!'
      redirect_to merchant_user_items_path
    else
      flash[:error] = @item.errors.full_messages.to_sentence
      render :edit
    end
  end

  def activate_deactivate
    if params[:activate_deactivate] == 'deactivate'
      item = Item.find(params[:item_id])
      item.toggle!(:active?)
      flash[:notice] = "#{item.name} is now deactivated and is no longer for sale."
    elsif params[:activate_deactivate] == 'activate'
      item = Item.find(params[:item_id])
      item.toggle!(:active?)
      flash[:notice] = "#{item.name} is now activated and available for sale."
    end
    redirect_to merchant_user_items_path
  end

  def disable_item
    item = Item.find(params[:item_id])
    item.toggle!(:enabled?)
    flash[:notice] = "#{item.name} is now removed from #{item.merchant.name}'s online inventory."
    redirect_to merchant_user_items_path
  end

  private

  def item_params
    params[:image] = 'https://bit.ly/34a6p1g' if params[:image] == ''
    params.permit(:name, :description, :price, :inventory, :image)
  end
end

app/views/items/edit.html.erb
<h1>Edit <%=link_to @item.name, "/items/#{@item.id}" %></h1>

<center>
  <%= form_tag "/items/#{@item.id}", method: :patch  do %>
    <%= label_tag :name %>
    <%= text_field_tag :name, "#{@item.name}"%>

    <%= label_tag :description %>
    <%= text_field_tag :description, "#{@item.description}" %>

    <%= label_tag :price %>
    <%= text_field_tag :price, "#{number_to_currency(@item.price)}" %>

    <%= label_tag :image %>
    <%= text_field_tag :image, "#{@item.image}" %>

    <%= label_tag :inventory %>
    <%= text_field_tag :inventory, "#{@item.inventory}" %>

    <%= submit_tag 'Update Item' %>
  <% end %>
</center>

app/views/items/index.html.erb
<% if @merchant %>
  <h1><%= link_to @merchant.name, merchant_path(@merchant.id) %><span> Items</span></h1>
  <h3 align="center"><%= link_to "Add New Item", new_merchant_item_path(@merchant.id) %></h3>
<% else %>
  <h1>All Items</h1>
<% end %>

<section class="grid-container">
  <section id="most-popular-items">
    <h3 align="center">Most Popular Items: </h3>
    <% @items.five_most_popular_items.each do |item| %>
      <p align="center"><%= item.name %>: <%= item.purchase_amount %> purchased</p>
    <% end %>
  </section>

  <section id="least-popular-items">
    <h3 align="center">Least Popular Items: </h3>
    <% @items.five_least_popular_items.each do |item| %>
      <p align="center"><%= item.name %>: <%= item.purchase_amount %> purchased</p>
    <% end %>
  </section>
</section>
<hr>

<section class="grid-container">
  <% @items.each do |item| %>
    <% if item.enabled? %>
      <% if item.active? %>
        <section class = "grid-item" id= 'item-<%=item.id%>'>
          <h2> <%=link_to item.name, item_path(item.id) %> </h2>
          <p>Sold by: <%=link_to item.merchant.name, merchant_path(item.merchant.id) %></p>
          <%= link_to(image_tag(item.image), item_path(item.id)) %>
          <p> <%= item.description unless @merchant%> </p>
          <p>Price: <%=number_to_currency(item.price) %> </p>
          <p>Inventory: <%= item.inventory %> </p>
          <% if item.active? %>
            <p>Active</p>
          <% else %>
            <p>Inactive</p>
          <% end %>
        </section>
        <% end %>
      <% end %>
    <% end %>
</section>

app/views/items/new.html.erb
<h1>Create New Item For <%=link_to @merchant.name, "/merchants/#{@merchant.id}" %></h1>

<center>
  <%= form_tag "/merchants/#{@merchant.id}/items", method: :post do %>
    <%= label_tag :name %>
    <%= text_field_tag :name%>

    <%= label_tag :description %>
    <%= text_field_tag :description %>

    <%= label_tag :price %>
    <%= text_field_tag :price %>

    <%= label_tag :image %>
    <%= text_field_tag :image %>

    <%= label_tag :inventory %>
    <%= text_field_tag :inventory %>

    <%= submit_tag 'Create Item' %>
  <% end %>
</center>

app/views/items/show.html.erb
<h1><%= link_to @item.name, "/items/#{@item.id}" %></h1>
<p align="center">Sold by: <%=link_to @item.merchant.name, "/merchants/#{@item.merchant.id}" %> </p>
<section align = "center" id = "average-rating">
  <p>Average Rating: <%= @item.average_review %></p>
</section>
<center>
  <section class = "item-show-grid">
    <section class = "item-show-item">
      <img src= <%= @item.image %>>
    </section>
    <section style="text-align:left" class = "item-show-item">
      <p><%= @item.description %></p>
      <p>Price: <%= number_to_currency(@item.price)%> </p>
      <p>Inventory: <%= @item.inventory %> </p>
      <% if @item.active? %>
        <p style= "color:green">Active</p>
      <% else %>
        <p style= "color:red">Inactive</p>
      <% end %>
      <% if merchant_admin? || merchant_employee? || site_admin? %>
        <p><%= link_to "Edit Item", "/items/#{@item.id}/edit" %></p>
        <p><%= link_to "Delete Item", "/items/#{@item.id}", method: :delete if @item.no_orders?%></p>
      <% end %>
      <% if current_user %>
        <%= link_to "Add Review", "/items/#{@item.id}/reviews/new" %>
      <% end %>
      <% if @item.active? && !site_admin? %>
        <%= button_to "Add To Cart", "/cart/#{@item.id}", method: :post %>
      <% end %>
    </section>
  </section>
</center>
<center>
<section class = "review-stats">
  <%if @item.reviews.empty? %>
    <h3>This item has not yet been reviewed.</h3>
  <% else %>
    <section class = "top-three-reviews">
      <h2>Top 3 Reviews</h2>
      <% @item.sorted_reviews(3, :desc).each do |review| %>
        <h3><%= "#{review.rating}-#{review.title}" %></h3>
      <% end %>
    </section>
    <section class = "bottom-three-reviews">
      <h2>Bottom 3 Reviews</h2>
      <% @item.sorted_reviews(3, :asc).each do |review| %>
        <h3><%= "#{review.rating}-#{review.title}" %></h3>
      <% end %>
    </section>
  </section>
  <section class = "list-reviews">
    <h2>All Reviews</h2>
    <% @item.reviews.each do |review| %>
      <section id= 'review-<%=review.id%>'>
        <%= review.title %>
        <%= review.content %>
        Rating: <%= review.rating %>/5
        <% if current_user %>
          <%= link_to "Edit", "/reviews/#{review.id}/edit" %>
          <%= link_to "Delete", "/reviews/#{review.id}", method: :delete %>
        <% end %>
      </section>
    <% end %>
  <% end %>
</section>
</center>